name: WebdriverIO Telnyx Tests

on:
  push:
    branches: [ main ]

jobs:
  tests-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '16.15.0'
      - name: Install dependencies
        run: npm ci
           
      - name: run tests on Google Chrome
        run: npm run allTestsChromeHeadless
      # - name: run tests on Firefox
      #   run: npm run allTestsFirefoxHeadless

      - name: Generate report
        if: always()
        run: npm run allure-generate
      - name: Upload directory with report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: ./allure-report
          retention-days: 5

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report      
        
            